### ISSUE TITLE
parameter "output target" crashes Gimp 2.10.14

### ISSUE THREAD

**Issue by bootchk** [carlobaldassi/gimp-lqr-plugin#3]
See Gimp #4496.

I have limited understanding, but it seems to indicate you need to substitute '_' for the space character in the name of the argument "output target".  I could be wrong, maybe Gimp will change to allow the space.

**Comment by gimplyworxs** [comment]
In src/main.c line 182: first occurence of output target has to replaced by output_target.
Then compiled ... and works (tested GIMP 2.10.12 linux)

https://github.com/carlobaldassi/gimp-lqr-plugin/blob/3590a1e260e8f4dfbd937c341c0774cdae96ef39/src/main.c#L182

**Comment by koiuo** [comment]
This is about to be worked around in GIMP with this commit:
https://gitlab.gnome.org/GNOME/gimp/-/commit/1af8ad8905352de95bb827beb488aed8997cad71

But still the issue has to be fixed in this plugin (GIMP will issue warnings after the workaround commit is released).

FWIW, if you are on Arch, you can use my AUR package for now
https://aur.archlinux.org/packages/gimp2.10-plugin-lqr/
